# Generated by Django 5.1 on 2024-08-15 18:24

import django.db.models.deletion
import django.utils.timezone
import processes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('s3_key', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('file_upload', models.FileField(default='processed_folder/alfa.xlsx', storage=processes.models.S3Storage(), upload_to='processed_folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
