# Generated by Django 5.1 on 2024-08-16 11:39

import processes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processeddata',
            options={'verbose_name': 'Processed Data', 'verbose_name_plural': 'Processed Data'},
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='file_upload',
            field=models.FileField(blank=True, null=True, storage=processes.models.S3Storage(), upload_to='processed_folder'),
        ),
    ]
