# Generated by Django 5.1 on 2024-09-05 11:16

import django.db.models.deletion
import django.utils.timezone
import polcyprocess.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('s3_key', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_type', models.CharField(choices=[('INCOME_POLICY_PRO', 'Income'), ('EXPENSE_POLICY_PRO', 'Expense')], max_length=20)),
                ('file_upload', models.FileField(blank=True, null=True, storage=polcyprocess.models.S3Storage(), upload_to='policy_processed_folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processed Data',
                'verbose_name_plural': 'Processed Data',
            },
        ),
    ]
