# Generated by Django 5.1 on 2024-09-05 06:36

import django.db.models.deletion
import policy.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomePolicyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('INC_P_PREV_MONTH', 'Previous Month'), ('INC_P_MAIN', 'Main'), ('INC_P_DATA_CASE', 'Data Case'), ('INC_P_RETENTION', 'Retention'), ('INC_P_COMISSION', 'Comission')], max_length=30)),
                ('file_upload', models.FileField(storage=policy.models.S3Storage(), upload_to='income_policy_folder')),
                ('filename', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
