# Generated by Django 5.1 on 2024-08-15 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('s3_key', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_type', models.CharField(choices=[('MAIN', 'Main'), ('OVERRIDE', 'Override'), ('PREV_MONTH', 'Previous Month'), ('SECURITY', 'Security'), ('RETIREMENT', 'Retirement')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('s3_key', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('income_type', models.CharField(choices=[('PREV_MONTH', 'Previous Month'), ('DATA_CASE', 'Data Case'), ('MAIN', 'Main')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('s3_key', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
