# Generated by Django 5.1 on 2024-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseupload',
            name='file_upload',
            field=models.FileField(default='expense_folder/alfa.xlsx', upload_to='expense_folder'),
        ),
        migrations.AddField(
            model_name='incomeupload',
            name='file_upload',
            field=models.FileField(default='income_folder/alfa.xlsx', upload_to='income_folder'),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='file_upload',
            field=models.FileField(default='processed_folder/alfa.xlsx', upload_to='processed_folder'),
        ),
    ]
