# Generated by Django 5.1 on 2024-08-15 14:37

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_expenseupload_file_upload_incomeupload_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseupload',
            name='file_upload',
            field=models.FileField(default='expense_folder/alfa.xlsx', storage=uploads.models.S3Storage(), upload_to='expense_folder'),
        ),
        migrations.AlterField(
            model_name='incomeupload',
            name='file_upload',
            field=models.FileField(default='income_folder/alfa.xlsx', storage=uploads.models.S3Storage(), upload_to='income_folder'),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='file_upload',
            field=models.FileField(default='processed_folder/alfa.xlsx', storage=uploads.models.S3Storage(), upload_to='processed_folder'),
        ),
    ]
