# Generated by Django 5.1 on 2024-08-15 18:24

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_expenseupload_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseupload',
            name='file_upload',
            field=models.FileField(storage=uploads.models.S3Storage(), upload_to='expense_folder'),
        ),
        migrations.AlterField(
            model_name='expenseupload',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expenseupload',
            name='s3_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expenseupload',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incomeupload',
            name='file_upload',
            field=models.FileField(storage=uploads.models.S3Storage(), upload_to='income_folder'),
        ),
        migrations.AlterField(
            model_name='incomeupload',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incomeupload',
            name='s3_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incomeupload',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='ProcessedData',
        ),
    ]
