# Generated by Django 5.1 on 2024-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_alter_expenseupload_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseupload',
            name='expense_type',
            field=models.CharField(choices=[('EXP_PREV_MONTH', 'Previous Month'), ('EXP_OVERRIDE', 'Override'), ('EXP_SECURITY', 'Security'), ('EXP_RETIREMENT', 'Retirement'), ('EXP_MAIN', 'Main')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incomeupload',
            name='income_type',
            field=models.CharField(choices=[('INC_PREV_MONTH', 'Previous Month'), ('INC_DATA_CASE', 'Data Case'), ('INC_MAIN', 'Main')], max_length=20),
        ),
    ]
