# Generated by Django 5.1 on 2024-08-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_alter_expenseupload_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeupload',
            name='income_type',
            field=models.CharField(choices=[('INC_PREV_MONTH', 'Previous Month'), ('INC_LIFE', 'Life insurance'), ('INC_NON_LIFE', 'Non Life Insurance'), ('INC_MAIN', 'Main'), ('INC_RETENTION', 'Retention'), ('INC_COMISSION', 'Comission')], max_length=20),
        ),
    ]
