# Generated by Django 5.1 on 2024-09-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_alter_incomeupload_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseupload',
            name='expense_type',
            field=models.CharField(choices=[('EXP_PREV_MONTH', 'Previous Month'), ('EXP_OVERRIDE', 'Override'), ('EXP_SECURITY', 'Security'), ('EXP_RETIREMENT', 'Retirement'), ('EXP_MAIN', 'Main'), ('EXP_RETENTION', 'Retention'), ('EXP_COMISSION', 'Comission'), ('EXP_CONTRACTS', 'Contract')], max_length=20),
        ),
    ]
